variable "project_name" {}
variable "env" {}
variable "region" {}
variable "vpc_id" {}
variable "subnet_ids" {}
variable "sec_grp_id" {}
variable "rds_db_az" {}
variable "rds_endpoint" {}
variable "rds_db_name" {}
variable "dynamo_db_name" {}
