name: Luxe-ecommerce terraform CI/CD

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "*.md", "infrastructure/.gitignore", ".github/**", "documentation/**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Check Terraform file Format
        run: terraform fmt -check -recursive
        working-directory: infrastructure/

      - name: AWS Login (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify identity test
        run: aws sts get-caller-identity
        
      - name: Initialize Terraform
        run: terraform init
        working-directory: infrastructure/

      - name: Terraform Validate
        run: terraform validate
        working-directory: infrastructure/

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: infrastructure/

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        working-directory: infrastructure/